# Hipchat API token
hipchat: oias8dnapsdn9aods8yona8sdb

# Mapping from names used in files to Hipchat mention names
mapping:
  John: DovOpsFromSomewhere
  Tytek: JustMe
  Tomek: NobodyWillNeverRedThis
  Romek: WhoCares
